[General]
bypass-system = true
skip-proxy = 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,*.local,localhost,captive.apple.com,www.baidu.com
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,239.255.255.250/32,255.255.255.255/32
dns-server = https://dns.alidns.com/dns-query,https://doh.pub/dns-query
fallback-dns-server = https://dns.alidns.com/dns-query,https://doh.opendns.com/dns-query
hijack-dns = *:53
icmp-auto-reply = true
private-ip-answer = true
dns-direct-fallback-proxy = false
udp-policy-not-supported-behaviour = REJECT
tcp-fast-open = true
dns-cache = true

[Proxy Group]
WECHAT = select,DIRECT
即时通讯 = url-test,interval=1200,tolerance=150,url= https://www.cloudflare.com/cdn-cgi/trace,policy-regex-filter=(?i)英|uk
智能助手 = url-test,interval=1200,tolerance=150,url= https://www.cloudflare.com/cdn-cgi/trace,policy-regex-filter=(?i)美|us|新|sg|日|jp|英|uk|澳|au|韩|kr
苹果服务 = select,DIRECT
GOOGLE = url-test,interval=1200,tolerance=150,url= https://www.cloudflare.com/cdn-cgi/trace,policy-regex-filter=(?i)美|us|新|sg|日|jp|英|uk|澳|au|韩|kr
国内媒体 = select,DIRECT
国内规则 = select,DIRECT
国际媒体 = url-test,interval=1200,tolerance=150,url= https://www.cloudflare.com/cdn-cgi/trace,policy-regex-filter=(?i)美|us|新|sg|日|jp|英|uk|澳|au|韩|kr
国际规则 = fallback,interval=1200,tolerance=150,url= https://www.cloudflare.com/cdn-cgi/trace,policy-regex-filter=(?i).+

[Rule]
RULE-SET,https://pomelo.us.kg/Rules/Lan.list,DIRECT
RULE-SET,https://pomelo.us.kg/Rules/WeChat.list,WECHAT
RULE-SET,https://pomelo.us.kg/Rules/Socials.list,即时通讯
RULE-SET,https://pomelo.us.kg/Rules/AI.list,智能助手
RULE-SET,https://pomelo.us.kg/Rules/Apple.list,苹果服务
RULE-SET,https://pomelo.us.kg/Rules/Google.list,GOOGLE
RULE-SET,https://pomelo.us.kg/Rules/ChinaMedia.list,国内媒体
RULE-SET,https://pomelo.us.kg/Rules/China.list,国内规则
RULE-SET,https://pomelo.us.kg/Rules/GlobalMedia.list,国际媒体
RULE-SET,https://pomelo.us.kg/Rules/Global.list,国际规则
GEOIP,CN,国内规则
FINAL,国际规则

[Host]
localhost = 127.0.0.1